FROM node:11-alpine
COPY . .
RUN npm install
EXPOSE 8080
CMD ["npm","start"]

ENV AWS_BUCKET_NAME bryaalbani
ENV AWS_BUCKET_REGION us-east-1
ENV AWS_ACCESS_KEY AKIAXBDX4GV6KNZC7XFX
ENV AWS_SECRET_KEY 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
